---

- name: Installieren mehrerer PHP-Anwendungen
  hosts: webservers
  become: true
  vars:
    uebungnr: "04"
  tasks:

    - name: Copy application
      template:
        src: "{{ playbook_dir }}/../templates/{{ item }}"
        dest: /var/www/html
      with_items:
        - phpinfo.php
        - database.php
        - index.php


    - debug:
        msg: "Die URL lautet: http://{{ ansible_host }}/index.php"
