
# move this file to 'configuration.yml' and fill in real data

ami_owner: "099720109477"
#ami_name: "ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server"
#ami_version: "20210315.1"
ami_name: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server"
ami_version: "20230216"
regions: [ "eu-central-1", "eu-west-1" , "eu-west-2", "eu-west-3", "eu-north-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2" ]

attendee_prefix: attendee_
infra_name: "clt_lab"
vpc_cidr: "10.1.0.0/16"
subnet_cidr: "10.1.0.0/22"
year: 2023
mail_from: "Name <email@host>"
mail_subject_credentials: "CLT {{ year }} Ansible Workshop - Zugangsdaten"
mail_subject_prerequesites: "CLT {{ year }} Ansible Workshop - Vorbereitungen"
contact_email: "from@email"
workshop_weekday: "Sonntag"
workshop_date: "12. März {{ year }}"
workshop_time: "10:00"
workshop_room: "W1"
workshop_id: "141"
ansible_min_version: "2.9"
