---

- name: prerequesites
  hosts: localhost
  gather_facts: false

  vars:

  tasks:

  - name: include configuration
    include_vars:
      file: configuration.yml

  - name: include attendees
    include_vars:
      file: attendees.yml

  - name: send email
    mail:
      from: "{{ mail_from }}"
      to: "{{ _attendee['name'] }}"
      charset: utf8
      subject: "{{ mail_subject_prerequesites }}"
      body: "{{lookup('template', 'templates/prereq_mail.txt')}}"
    loop: "{{ attendees }}"
    loop_control:
      loop_var: _attendee
      label: "{{ _attendee.id }} - {{ _attendee.name }}"
